name: Lint

on:
  workflow_call:
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - uses: adombence/.github/.github/actions/npm-ci-cache@main
      - run: npm run lint